apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qb217ynxe-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qb217ynxe-go 
  name: qb217ynxe-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qb217ynxe-go 
